/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/json_type_def.rs:4
-- pgx_json_schema::json_type_def::jtd_is_valid
CREATE OR REPLACE FUNCTION "jtd_is_valid"(
	"schema" jsonb, /* pgx::datum::json::JsonB */
	"instance" jsonb /* pgx::datum::json::JsonB */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jtd_is_valid_wrapper';

-- src/json_type_def.rs:13
-- pgx_json_schema::json_type_def::jtd_get_errors
CREATE OR REPLACE FUNCTION "jtd_get_errors"(
	"schema" jsonb, /* pgx::datum::json::JsonB */
	"instance" jsonb /* pgx::datum::json::JsonB */
) RETURNS TABLE (
	"instance_path" text,  /* alloc::string::String */
	"schema_path" text  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jtd_get_errors_wrapper';

-- src/json_schema.rs:4
-- pgx_json_schema::json_schema::json_schema_is_valid
CREATE OR REPLACE FUNCTION "json_schema_is_valid"(
	"schema" jsonb, /* pgx::datum::json::JsonB */
	"instance" jsonb /* pgx::datum::json::JsonB */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'json_schema_is_valid_wrapper';

-- src/json_schema.rs:9
-- pgx_json_schema::json_schema::json_schema_get_errors
CREATE OR REPLACE FUNCTION "json_schema_get_errors"(
	"schema" jsonb, /* pgx::datum::json::JsonB */
	"instance" jsonb /* pgx::datum::json::JsonB */
) RETURNS TABLE (
	"error_value" jsonb,  /* pgx::datum::json::JsonB */
	"description" text,  /* alloc::string::String */
	"details" text,  /* alloc::string::String */
	"instance_path" text,  /* alloc::string::String */
	"schema_path" text  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'json_schema_get_errors_wrapper';

-- src/avro.rs:5
-- pgx_json_schema::avro::avro_is_valid
CREATE OR REPLACE FUNCTION "avro_is_valid"(
	"schema" jsonb, /* pgx::datum::json::JsonB */
	"instance" jsonb /* pgx::datum::json::JsonB */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'avro_is_valid_wrapper';
